all_raised = 0
data = (tuple(line.split(";")) for line in open('dataset') if line.split(";")[7] == 'a\n')
print(all_raised)
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))
# print(*data)
